# Generated by Django 4.1.7 on 2023-03-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.FloatField(help_text='En heures'),
        ),
    ]
