# Generated by Django 4.1.7 on 2023-03-13 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.FloatField(help_text='En heures', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
