# Generated by Django 4.1.7 on 2023-03-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('course', '0004_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='student.student'),
        ),
    ]
