# Generated by Django 4.1.7 on 2023-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_courses'),
        ('course', '0006_remove_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='student.student'),
        ),
    ]
