# Generated by Django 4.1.7 on 2023-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_course_students'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='course.course'),
        ),
    ]
