# Generated by Django 4.1.7 on 2023-03-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
